#!/usr/bin/env bash

## .bashrc

cat <<'EOF' >>~/.bashrc

# fzf
export FZF_DEFAULT_OPTS="--multi --bind=alt-k:up,alt-j:down --bind 'home:last,end:first' --bind 'ctrl-o:execute(vim {}),ctrl-]:execute(sudo vim {})' --preview 'echo {}' --preview-window top:40%:hidden:wrap --bind 'ctrl-p:toggle-preview'"
source <(fzf --bash)

EOF

cat <<'EOF' | sudo tee -a /root/.bashrc

# fzf
export FZF_DEFAULT_OPTS="--multi --bind=alt-k:up,alt-j:down --bind 'home:last,end:first' --bind 'ctrl-o:execute(vim {}),ctrl-]:execute(sudo vim {})' --preview 'echo {}' --preview-window top:40%:hidden:wrap --bind 'ctrl-p:toggle-preview'"
source <(fzf --bash)

EOF

## ~/.local/bin

mkdir -p ~/.local/bin

files=(
  "fzf"
  "fzflog"
)

for file in "${files[@]}"; do
	chmod 777 "$file"
	sudo cp "$file" /usr/bin
done
