#!/usr/bin/env bash

## .bashrc

cat <<'EOF' >>~/.bashrc

# starship
eval "$(starship init bash)"

EOF

cat <<'EOF' | sudo tee -a /root/.bashrc

# starship
eval "$(starship init bash)"

EOF

## ~/.local/bin ~/.config

mkdir -p ~/.local/bin
mkdir -p ~/.config
sudo mkdir -p /root/.config

chmod 777 "starship"
sudo cp "starship" /usr/bin

cp ./starship.toml ~/.config
sudo cp ./starship.toml /root/.config

