#!/usr/bin/env bash

    case "$1" in
        -f)
            shift
            { tail -f -n 0 "$@" & cat "$@"; } | fzf -i +s -e --tac
            ;;
        *)
            cat "$@" | fzf -i +s -e --tac
            ;;
    esac


